[package]
name = "wfn_eng"
version = "0.1.0"
authors = ["Cerek Hillen <cerekh@gmail.com>"]

[dependencies]
vulkano-shader-derive = "0.9"
vulkano = "0.9"
vulkano-win = "0.9"
winit = "0.11.2"
image = "0.19"
